export const SELECT_THICKNESS = 'SELECT_THICKNESS';
export const SELECT_COLOR = 'SELECT_COLOR';
export const RESET_CANVAS = 'RESET_CANVAS';
export const SELECT_PENCIL = 'SELECT_PENCIL';
export const SELECT_ERASE = 'SELECT_ERASE';
